stages:
  - build
  - deploy

variables:
  BUILD_DIR: $CI_PROJECT_DIR/build

build:admin:
  stage: build
  image: theotherjim/node-gulp-jspm
  only:
    - master
  script:
    - cp -r . /var/lib/admin
    - cd /var/lib/admin
    - npm install
    - jspm install
    - ./node_modules/.bin/gulp build
    - mkdir -p $BUILD_DIR/admin
    - cp -r ./dist/* $BUILD_DIR/admin

  artifacts:
    untracked: true
    expire_in: 1 hour


deploy:production:
  image: gitlab/dind
  stage: deploy
  only:
    - master
  services:
    - docker:dind
  variables:
    IMAGE_TAG: "business"
  script:
    - export TAG=`git describe --abbrev=0 --tags`
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build --pull -t $CI_REGISTRY_IMAGE:$TAG .
    - docker tag $CI_REGISTRY_IMAGE:$TAG $CI_REGISTRY_IMAGE:$IMAGE_TAG
    - docker push $CI_REGISTRY_IMAGE:$TAG
    - docker push $CI_REGISTRY_IMAGE:$IMAGE_TAG
  dependencies:
    - build:admin
